[Variables]
Author=Vin Star
LocationCode=USCA0638
UnitOfMeasure=f
ScrollMouseIncrement=0.01
Format=#I
Hidden=1
Hidden2=0
Player=Spotify
Color1=255,255,255
Color2=240,0,0

______________________________________________________________________


Icon1NameAndPath=#@#\My Computer.png
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\Recycle Bin.png
LocationPath2=[Shell:::{645FF040-5081-101B-9F08-00AA002F954E}]

Icon3NameAndPath=#@#\spotify.png
LocationPath3=[www.spotify.com]

Icon4NameAndPath=#@#\youtube.png
LocationPath4=[www.youtube.com]

Icon5NameAndPath=#@#\discord.png
LocationPath5=[www.discord.com]

Icon6NameAndPath=#@#\Google.png
LocationPath6=!Execute ["https://google.com"]

Icon7NameAndPath=#@#\settings.png
LocationPath7=["C:\Users\VIN STAR\Desktop\Settings.lnk"]
